@php
    $setupSteps = collect($setup['steps'] ?? []);
    $setupNext = $setupSteps->first(static fn (array $step): bool => $step['required'] && ! $step['complete']);
@endphp

<x-layouts::app :title="__('Dashboard')">
    <x-app.page :title="__('Setup and operations workspace')" :description="__('Finish Setup / Master Data definitions before Daily Operations / Transactions.')" :eyebrow="__('Workspace')" :badge="__('Setup first')" badge-color="primary" max-width="7xl" data-guide="dashboard-header">
        <section class="rounded-2xl border border-primary/20 bg-primary-soft/30 p-5 shadow-sm sm:p-6" data-guide="dashboard-initial-setup"><div class="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div class="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{{ __('Setup / Master Data') }}</div><flux:heading class="mt-2" size="lg">{{ __('Initial setup progress') }}</flux:heading><flux:text class="mt-1"><span dir="ltr">{{ $setup['completed_count'] ?? 0 }} / {{ $setup['required_count'] ?? 0 }}</span> {{ __('required steps completed') }}. {{ __('Use the checklist to configure or review each persisted definition.') }}</flux:text></div><flux:button :href="route('initial-setup')" variant="primary" wire:navigate data-guide="dashboard-initial-setup-action">{{ __('Open setup checklist') }}</flux:button></div><div class="mt-5 grid gap-3 sm:grid-cols-3">@foreach ($setupSteps->filter(static fn (array $step): bool => $step['required'])->take(3) as $step)<div class="rounded-xl border border-border bg-surface/80 p-3"><div class="flex items-center justify-between gap-2"><span class="text-sm font-semibold">{{ $step['label'] }}</span><span class="text-xs font-medium {{ $step['status'] === 'completed' ? 'text-emerald-700 dark:text-emerald-300' : ($step['status'] === 'blocked' ? 'text-rose-700 dark:text-rose-300' : 'text-amber-700 dark:text-amber-300') }}">{{ $step['status_label'] }}</span></div>@if ($step['route'] && $step['can_access'])<a class="mt-2 inline-flex text-xs font-semibold text-primary hover:underline" href="{{ $step['route'] }}" wire:navigate>{{ $step['cta_label'] }}</a>@endif</div>@endforeach</div></section>

        <section aria-labelledby="operations-heading" class="overflow-hidden rounded-2xl border border-border bg-surface/95 shadow-card" data-guide="dashboard-operations"><div class="border-b border-border bg-surface-muted/35 px-5 py-5 sm:px-6"><flux:heading id="operations-heading" size="lg">{{ __('Daily Operations / Transactions') }}</flux:heading><flux:text class="mt-1">{{ __('Sales, purchase orders, inventory movements, parties, settlements, and returns are operational workflows kept separate from setup definitions.') }}</flux:text></div><ul class="divide-y divide-border"><li class="grid gap-2 px-5 py-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center sm:px-6"><div><p class="font-semibold text-text-primary">{{ __('Daily operations') }}</p><p class="mt-1 text-sm leading-6 text-text-muted">{{ __('Open operational workspaces only when the relevant setup and permissions are ready.') }}</p></div><span class="w-fit text-sm font-semibold text-text-muted">{{ __('Separate workspace') }}</span></li><li class="grid gap-2 px-5 py-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center sm:px-6"><div><p class="font-semibold text-text-primary">{{ __('Review and administration') }}</p><p class="mt-1 text-sm leading-6 text-text-muted">{{ __('Use approvals, reports, and administration according to your role and scope.') }}</p></div><span class="w-fit text-sm font-semibold text-text-muted">{{ __('Permission controlled') }}</span></li></ul></section>
    </x-app.page>
</x-layouts::app>
