<?php

declare(strict_types=1);

namespace App\Modules\Inventory\Actions;

use App\Modules\Inventory\Models\InventoryAdjustment;
use App\Modules\Inventory\Models\InventoryAdjustmentLine;
use App\Modules\Inventory\Models\StockCount;
use App\Modules\Inventory\Models\StockBalance;
use App\Modules\Inventory\Models\StockMovement;
use App\Modules\Platform\Actions\ApproveRequest;
use App\Modules\Platform\Actions\AllocateDocumentNumber;
use App\Modules\Platform\Actions\RecordAuditEvent;
use App\Modules\Platform\Enums\ApprovalState;
use App\Modules\Platform\Models\ApprovalRecord;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use InvalidArgumentException;

final class ReconcileStockCountAction
{
    public function __construct(private readonly AssertInventoryStoreScope $scope) {}

    public function execute(int $id): StockCount
    {
        Gate::authorize('stock_counts.reconcile');

        return DB::transaction(function () use ($id): StockCount {
            $count = StockCount::query()->with('lines')->lockForUpdate()->findOrFail($id);
            if ($count->store_id === null) {
                throw new InvalidArgumentException(__('This Local Demo count must target a store before reconciliation.'));
            }
            $this->scope->execute($count->store_id);
            if ($count->status === 'reconciled') {
                return $count->fresh(['store', 'lines.product']);
            }
            if ($count->status !== 'submitted') {
                throw new InvalidArgumentException(__('Only submitted stock counts can be reconciled.'));
            }
            if ($count->assigned_to === Auth::id()) {
                throw new InvalidArgumentException(__('The stock counter cannot approve the same reconciliation.'));
            }
            foreach ($count->lines as $line) {
                $balance = StockBalance::query()
                    ->where('product_id', $line->product_id)
                    ->where('store_id', $count->store_id)
                    ->lockForUpdate()
                    ->first();
                $movementQuantity = StockMovement::query()
                    ->where('product_id', $line->product_id)
                    ->where('store_id', $count->store_id)
                    ->where('posted_at', '>', $count->reference_at)
                    ->sum('quantity');
                if (bccomp((string) $movementQuantity, (string) $line->movement_quantity_after_reference, 6) !== 0) {
                    throw new InvalidArgumentException(__('Stock changed after count submission. Submit the count again before reconciliation.'));
                }
                unset($balance);
            }
            $approval = ApprovalRecord::query()
                ->where('source_type', 'stock_counts')
                ->where('source_id', (string) $count->id)
                ->where('requested_action', 'reconcile')
                ->where('approval_state', ApprovalState::Pending->value)
                ->lockForUpdate()
                ->firstOrFail();
            $adjustment = InventoryAdjustment::query()->create([
                'adjustment_number' => app(AllocateDocumentNumber::class)->execute('inventory_adjustment'),
                'store_id' => $count->store_id,
                'adjustment_type' => 'count_adjustment',
                'status' => 'approved',
                'reason_code' => 'count_variance',
                'reason_notes' => 'Local Demo count reconciliation; uncounted products are excluded and never auto-zeroed.',
                'allow_negative' => false,
                'created_by' => $count->created_by,
                'submitted_by' => $count->assigned_to,
                'approved_by' => Auth::id(),
                'submitted_at' => $count->submitted_at,
                'approved_at' => now(),
                'idempotency_key' => 'DEMO-COUNT-ADJUSTMENT:'.$count->id,
                'lock_version' => 2,
                'notes' => 'DEMO ONLY. Generated by manager reconciliation.',
            ]);
            foreach ($count->lines as $line) {
                if (! $line->is_counted || $line->variance_quantity === null || bccomp((string) $line->variance_quantity, '0', 6) === 0) {
                    continue;
                }
                $adjustmentLine = InventoryAdjustmentLine::query()->create(['inventory_adjustment_id' => $adjustment->id, 'product_id' => $line->product_id, 'quantity_delta' => $line->variance_quantity, 'unit_cost' => null, 'before_on_hand' => $line->expected_quantity, 'after_on_hand' => bcadd((string) $line->expected_quantity, (string) $line->variance_quantity, 6)]);
                app(PostInventoryMovement::class)->execute($line->product_id, $count->store_id, (string) $line->variance_quantity, 'count_reconciliation', null, 'DEMO-COUNT-MOVEMENT:'.$count->id.':'.$line->id, StockCount::class, $count->id, $adjustmentLine->id);
            }
            $before = $count->only(['status', 'lock_version']);
            $count->update(['status' => 'reconciled', 'approved_by' => Auth::id(), 'reconciled_at' => now(), 'lock_version' => $count->lock_version + 1]);
            app(ApproveRequest::class)->execute($approval, (string) $before['lock_version'], decisionNote: __('Stock-count reconciliation approved.'));
            app(RecordAuditEvent::class)->execute('inventory', 'reconcile_stock_count', $count, $before, $count->only(['status', 'approved_by', 'reconciled_at', 'lock_version']), storeId: $count->store_id, metadata: ['adjustment_id' => $adjustment->id, 'uncounted_lines_preserved' => $count->lines->where('is_counted', false)->count(), 'approval_record_id' => $approval->id]);

            return $count->fresh(['store', 'lines.product']);
        });
    }
}
