<?php

declare(strict_types=1);

namespace App\Modules\Inventory\Actions;

use App\Modules\Inventory\Models\InventoryAdjustment;
use App\Modules\Inventory\Models\InventoryAdjustmentLine;
use App\Modules\Inventory\Models\StockCount;
use App\Modules\Platform\Actions\RecordAuditEvent;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use InvalidArgumentException;

final class ReconcileStockCountAction
{
    public function __construct(private readonly AssertInventoryStoreScope $scope) {}

    public function execute(int $id): StockCount
    {
        Gate::authorize('stock_counts.reconcile');

        return DB::transaction(function () use ($id): StockCount {
            $count = StockCount::query()->with('lines')->lockForUpdate()->findOrFail($id);
            if ($count->store_id === null) {
                throw new InvalidArgumentException(__('This Local Demo count must target a store before reconciliation.'));
            }
            $this->scope->execute($count->store_id);
            if ($count->status !== 'submitted') {
                throw new InvalidArgumentException(__('Only submitted stock counts can be reconciled.'));
            }
            if ($count->assigned_to === Auth::id()) {
                throw new InvalidArgumentException(__('The stock counter cannot approve the same reconciliation.'));
            }
            $adjustment = InventoryAdjustment::query()->create([
                'adjustment_number' => 'DEMO-COUNT-ADJ-'.$count->id,
                'store_id' => $count->store_id,
                'adjustment_type' => 'count_adjustment',
                'status' => 'approved',
                'reason_code' => 'count_variance',
                'reason_notes' => 'Local Demo count reconciliation; uncounted products are excluded and never auto-zeroed.',
                'allow_negative' => false,
                'created_by' => $count->created_by,
                'submitted_by' => $count->assigned_to,
                'approved_by' => Auth::id(),
                'submitted_at' => $count->submitted_at,
                'approved_at' => now(),
                'idempotency_key' => 'DEMO-COUNT-ADJUSTMENT:'.$count->id,
                'lock_version' => 2,
                'notes' => 'DEMO ONLY. Generated by manager reconciliation.',
            ]);
            foreach ($count->lines as $line) {
                if (! $line->is_counted || $line->variance_quantity === null || bccomp((string) $line->variance_quantity, '0', 6) === 0) {
                    continue;
                }
                $adjustmentLine = InventoryAdjustmentLine::query()->create(['inventory_adjustment_id' => $adjustment->id, 'product_id' => $line->product_id, 'quantity_delta' => $line->variance_quantity, 'unit_cost' => null, 'before_on_hand' => $line->expected_quantity, 'after_on_hand' => bcadd((string) $line->expected_quantity, (string) $line->variance_quantity, 6)]);
                app(PostInventoryMovement::class)->execute($line->product_id, $count->store_id, (string) $line->variance_quantity, 'count_reconciliation', null, 'DEMO-COUNT-MOVEMENT:'.$count->id.':'.$line->id, StockCount::class, $count->id, $adjustmentLine->id);
            }
            $before = $count->only(['status', 'lock_version']);
            $count->update(['status' => 'reconciled', 'approved_by' => Auth::id(), 'reconciled_at' => now(), 'lock_version' => $count->lock_version + 1]);
            app(RecordAuditEvent::class)->execute('inventory', 'reconcile_stock_count', $count, $before, $count->only(['status', 'approved_by', 'reconciled_at', 'lock_version']), storeId: $count->store_id, metadata: ['adjustment_id' => $adjustment->id, 'uncounted_lines_preserved' => $count->lines->where('is_counted', false)->count()]);

            return $count->fresh(['store', 'lines.product']);
        });
    }
}
