<section class="flex min-h-[42rem] min-w-0 flex-col overflow-hidden rounded-2xl bg-white shadow-xs ring-1 ring-zinc-200 dark:bg-zinc-900 dark:ring-zinc-800 xl:sticky xl:top-3 xl:max-h-[calc(100vh-5rem)]" aria-labelledby="pos-cart-heading">
    <div class="flex items-center justify-between gap-3 border-b border-zinc-100 p-4 dark:border-zinc-800"><div><flux:heading id="pos-cart-heading" size="lg">{{ __('Cart') }} <span class="text-zinc-400">({{ $cart->count() }})</span></flux:heading><p class="mt-0.5 text-xs text-zinc-500">{{ __('Each variation remains a separate SKU line.') }}</p></div>@if($cart->isNotEmpty())<button wire:click="clear" wire:confirm="{{ __('Clear every item from this cart?') }}" class="min-h-10 rounded-lg px-3 text-sm font-semibold text-rose-600 hover:bg-rose-50">{{ __('Clear cart') }}</button>@endif</div>
    @if($errors->has('cart') || $error)<div class="p-3 pb-0"><flux:callout variant="danger" icon="exclamation-triangle">{{ $errors->first('cart') ?: $error }}</flux:callout></div>@endif
    <div wire:loading class="space-y-3 p-3"><div class="h-28 animate-pulse rounded-xl bg-zinc-100 dark:bg-zinc-800"></div><div class="h-28 animate-pulse rounded-xl bg-zinc-100 dark:bg-zinc-800"></div></div>
    <div wire:loading.remove class="min-h-0 flex-1 space-y-3 overflow-y-auto p-3">
        @forelse($lines as $index => $line)
            @php
                $product = $line['product']; $family = $product->family(); $image = $product->effectiveMainImage(); $computed = $preview['lines'][$index] ?? null;
                $step = $product->fractional_quantity ? '0.001' : '1'; $up = bcadd($line['quantity'], $step, 6); $down = bcsub($line['quantity'], $step, 6);
                $display = $product->fractional_quantity ? rtrim(rtrim(number_format((float)$line['quantity'], 3, '.', ''), '0'), '.') : number_format((float)$line['quantity'], 0, '.', '');
            @endphp
            <article class="rounded-xl bg-zinc-50 p-3 ring-1 ring-zinc-200 dark:bg-zinc-950/60 dark:ring-zinc-800" data-cart-line="{{ $product->id }}"><div class="flex gap-3">@if($image)<img src="{{ route('pos.products.thumbnail', ['product' => $image->product_id, 'attachment' => $image->attachment_id]) }}" alt="" width="112" height="112" loading="lazy" class="size-14 shrink-0 rounded-lg object-cover">@else<div class="flex size-14 shrink-0 items-center justify-center rounded-lg bg-zinc-200 dark:bg-zinc-800"><flux:icon name="cube" class="size-6 text-zinc-400" /></div>@endif<div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><div><h3 class="line-clamp-2 text-sm font-bold">{{ app()->getLocale() === 'ar' ? $family->name_ar : $family->name_en }}</h3><p class="mt-0.5 font-mono text-xs text-zinc-500">{{ $product->item_code }}</p></div><div class="shrink-0 text-end text-sm font-extrabold"><x-money :amount="$computed['net_amount'] ?? '0.00'" :currency="$store?->branch?->currency ?? 'EGP'" /></div></div>@if($product->isVariant())<p class="mt-2 text-xs text-zinc-600 dark:text-zinc-300">{{ $product->localizedVariationLabel() }}</p>@endif</div></div>
            <div class="mt-3 flex items-center justify-between border-t border-zinc-200 pt-3 dark:border-zinc-800"><div class="inline-grid grid-cols-[2.5rem_3.5rem_2.5rem] overflow-hidden rounded-lg border border-zinc-300 bg-white dark:border-zinc-700 dark:bg-zinc-900"><button wire:click="quantity({{ $product->id }}, '{{ $down }}')" @disabled(bccomp($down, '0', 6) <= 0) class="min-h-10 text-lg disabled:opacity-30">−</button><span class="flex min-h-10 items-center justify-center border-x border-zinc-300 text-sm font-extrabold dark:border-zinc-700">{{ $display }}</span><button wire:click="quantity({{ $product->id }}, '{{ $up }}')" class="min-h-10 text-lg">+</button></div><button wire:click="remove({{ $product->id }})" class="flex min-h-10 items-center gap-1 rounded-lg px-2 text-xs font-semibold text-rose-600"><flux:icon name="trash" class="size-4" />{{ __('Remove') }}</button></div>
            @if($line['price']->open_price_allowed || auth()->user()->can('pos_sales.apply_discount'))<details class="mt-3 border-t border-zinc-200 pt-3 dark:border-zinc-800"><summary class="cursor-pointer text-xs font-bold text-cyan-700">{{ __('Adjust price or discount') }}</summary><div class="mt-3 grid gap-3">@can('pos_sales.apply_discount')<form method="POST" action="{{ route('pos.cart.discount') }}" class="grid gap-2">@csrf<input type="hidden" name="product_id" value="{{ $product->id }}"><input type="hidden" name="expected_revision" value="{{ (int)($line['cart']['discount_revision'] ?? 0) }}"><input type="hidden" name="discount_type" value="line"><div class="grid grid-cols-2 gap-2"><flux:input name="discount_amount" type="number" min="0.01" step="0.01" :label="__('Discount amount')" required /><flux:input name="reason" :label="__('Reason')" /></div><flux:button type="submit" size="sm" variant="subtle">{{ __('Apply discount') }}</flux:button></form>@endcan @can('pos_sales.open_price')@if($line['price']->open_price_allowed)<form method="POST" action="{{ route('pos.cart.open-price') }}" class="grid gap-2">@csrf<input type="hidden" name="product_id" value="{{ $product->id }}"><input type="hidden" name="expected_revision" value="{{ (int)($line['cart']['pricing_revision'] ?? 0) }}"><div class="grid grid-cols-2 gap-2"><flux:input name="amount" type="number" min="0.0001" step="0.0001" :label="__('Open price amount')" required /><flux:input name="reason" :label="__('Required reason')" required /></div><flux:button type="submit" size="sm" variant="subtle">{{ __('Set open price') }}</flux:button></form>@endif@endcan</div></details>@endif
            </article>
        @empty<div class="flex min-h-64 flex-col items-center justify-center px-6 text-center"><div class="flex size-14 items-center justify-center rounded-2xl bg-zinc-100 dark:bg-zinc-800"><flux:icon name="shopping-cart" class="size-7 text-zinc-400" /></div><p class="mt-4 font-bold">{{ __('Cart is empty') }}</p><p class="mt-1 text-sm text-zinc-500">{{ __('Scan a barcode or select a variation to begin.') }}</p></div>@endforelse
    </div>
    @if($preview)<div class="border-t border-zinc-200 bg-zinc-50 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950"><div class="flex items-center justify-between"><span class="text-sm font-semibold text-zinc-500">{{ __('Cart total') }}</span><span class="text-xl font-extrabold"><x-money :amount="$preview['total']" :currency="$store?->branch?->currency ?? 'EGP'" /></span></div></div>@endif
</section>
