<section class="flex min-h-[42rem] min-w-0 flex-col overflow-hidden rounded-2xl bg-white shadow-xs ring-1 ring-zinc-200 dark:bg-zinc-900 dark:ring-zinc-800" aria-labelledby="pos-products-heading">
    <div class="p-4 pb-3">
        <div class="flex items-center justify-between gap-3"><div><flux:heading id="pos-products-heading" size="lg">{{ __('Products') }}</flux:heading><p class="mt-0.5 text-xs text-zinc-500">{{ __('Scan a barcode or choose a product family.') }}</p></div><span class="rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-semibold tabular-nums dark:bg-zinc-800">{{ $products->count() }}</span></div>
        <form wire:submit="submitSearch" class="mt-3"><label for="live-pos-product-search" class="sr-only">{{ __('Scan or search by name, SKU, barcode, or option') }}</label><div class="relative"><flux:icon name="magnifying-glass" class="pointer-events-none absolute start-4 top-1/2 z-10 size-5 -translate-y-1/2 text-zinc-400" /><input id="live-pos-product-search" wire:model.live.debounce.250ms="search" autocomplete="off" inputmode="search" dir="auto" autofocus class="block min-h-12 w-full rounded-xl border border-zinc-300 bg-zinc-50 ps-12 pe-28 text-base outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-600/15 dark:border-zinc-700 dark:bg-zinc-950" placeholder="{{ __('Scan or search by name, SKU, barcode, or option') }}"><button type="submit" class="absolute end-1.5 top-1.5 min-h-9 rounded-lg bg-cyan-700 px-3 text-sm font-semibold text-white">{{ __('Search') }}</button></div></form>
        <nav class="mt-3 flex gap-2 overflow-x-auto pb-1" aria-label="{{ __('Product categories') }}"><button wire:click="chooseCategory(null)" class="inline-flex min-h-9 shrink-0 items-center rounded-lg px-3 text-sm font-semibold {{ $categoryId === null ? 'bg-cyan-700 text-white' : 'bg-zinc-100 dark:bg-zinc-800' }}">{{ __('All') }}</button>@foreach($categories as $category)<button wire:click="chooseCategory({{ $category->id }})" class="inline-flex min-h-9 shrink-0 items-center rounded-lg px-3 text-sm font-semibold {{ $categoryId === $category->id ? 'bg-cyan-700 text-white' : 'bg-zinc-100 dark:bg-zinc-800' }}">{{ app()->getLocale() === 'ar' ? $category->name_ar : $category->name_en }}</button>@endforeach</nav>
    </div>
    @if (! $context->isReady())
        <div class="px-4 pb-3"><flux:callout variant="warning" icon="exclamation-triangle">{{ $context->disabledReason ?? __('POS is not ready for selling.') }}</flux:callout></div>
    @endif
    @error('selection')<div class="px-4 pb-3"><flux:callout variant="danger" icon="exclamation-triangle">{{ $message }}</flux:callout></div>@enderror
    <div wire:loading class="px-4"><div class="grid grid-cols-2 gap-3 md:grid-cols-3"><div class="h-48 animate-pulse rounded-xl bg-zinc-100 dark:bg-zinc-800"></div><div class="h-48 animate-pulse rounded-xl bg-zinc-100 dark:bg-zinc-800"></div><div class="hidden h-48 animate-pulse rounded-xl bg-zinc-100 dark:bg-zinc-800 md:block"></div></div></div>
    <div wire:loading.remove class="min-h-0 flex-1 overflow-y-auto border-t border-zinc-100 p-4 dark:border-zinc-800 xl:max-h-[calc(100vh-12rem)]"><div class="grid grid-cols-2 gap-3 md:grid-cols-3 2xl:grid-cols-4">
        @forelse($products as $product)
            @php
                $isFamily = $product->isFamily();
                $price = $isFamily ? $familyRanges->get($product->id) : $simplePrices->get($product->id);
                $stock = $isFamily ? $familyStock->has($product->id) : (($balance = $simpleStock->get($product->id)) && bccomp(bcsub((string)$balance->on_hand, (string)$balance->reserved, 6), '0', 6) > 0);
                $image = $product->images->firstWhere('role', 'main') ?? $product->images->first() ?? ($isFamily ? $familyChildImages->get($product->id) : null);
            @endphp
            <article class="group flex min-w-0 flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white transition hover:border-cyan-300 hover:shadow-md dark:border-zinc-800 dark:bg-zinc-950" data-product-family="{{ $product->id }}">
                <div class="relative flex h-28 items-center justify-center overflow-hidden bg-zinc-100 text-zinc-400 dark:bg-zinc-800">@if($image)<img src="{{ route('pos.products.thumbnail', ['product' => $image->product_id, 'attachment' => $image->attachment_id]) }}" alt="" width="320" height="224" loading="lazy" class="h-full w-full object-cover">@else<div class="flex size-14 items-center justify-center rounded-2xl bg-zinc-200 dark:bg-zinc-700"><flux:icon name="cube" class="size-7" /></div>@endif<span class="absolute start-2 top-2 rounded-md px-2 py-1 text-[11px] font-bold {{ $stock ? 'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200' : 'bg-zinc-50 text-zinc-600 ring-1 ring-zinc-200' }}">{{ $stock ? __('In stock') : __('Out of stock') }}</span></div>
                <div class="flex flex-1 flex-col p-3"><h3 class="line-clamp-2 min-h-10 text-sm font-bold">{{ app()->getLocale() === 'ar' ? $product->name_ar : $product->name_en }}</h3><p class="mt-1 truncate text-xs text-zinc-500">{{ $product->item_code }}@if($isFamily) · {{ trans_choice(':count option|:count options', $product->active_variants_count, ['count' => $product->active_variants_count]) }}@endif</p><div class="mt-auto pt-3">@if($price)@if($isFamily)<div class="text-base font-extrabold tabular-nums">{{ number_format((float)$price->min_price, 2) }}@if((string)$price->min_price !== (string)$price->max_price) – {{ number_format((float)$price->max_price, 2) }}@endif {{ $store?->branch?->currency ?? 'EGP' }}</div>@else<div class="text-base font-extrabold tabular-nums"><x-money :amount="$price->amount" :currency="$store?->branch?->currency ?? 'EGP'" /></div>@endif@else<p class="text-xs font-semibold text-amber-700">{{ __('No approved price') }}</p>@endif
                @if($isFamily)<button wire:click="openFamily({{ $product->id }})" class="mt-3 min-h-10 w-full rounded-lg bg-cyan-700 px-3 text-sm font-bold text-white disabled:bg-zinc-300" @disabled(!$price || ! $context->isReady())>{{ __('Choose variation') }}</button>@else<button wire:click="addProduct({{ $product->id }})" class="mt-3 min-h-10 w-full rounded-lg bg-cyan-700 px-3 text-sm font-bold text-white disabled:bg-zinc-300" @disabled(!$price || !$stock || ! $context->isReady())>{{ __('Add to cart') }}</button>@endif</div></div>
            </article>
        @empty<div class="col-span-full flex min-h-64 flex-col items-center justify-center text-center"><flux:icon name="magnifying-glass" class="size-9 text-zinc-300" /><p class="mt-3 font-semibold">{{ __('No products available.') }}</p><p class="mt-1 text-sm text-zinc-500">{{ __('Try another name, child SKU, barcode, option, or category.') }}</p></div>@endforelse
    </div></div>

    @if($drawer)
        @php
            $selected = $selectedVariantId ? $drawer->variants->firstWhere('id', $selectedVariantId) : null;
            $selectedPrice = $selected ? $drawerPrices->get($selected->id) : null;
            $selectedStock = $selected ? $drawerStock->get($selected->id) : null;
            $selectedAvailable = $selectedStock ? bcsub((string)$selectedStock->on_hand, (string)$selectedStock->reserved, 6) : '0';
            $selectedImage = $selected?->effectiveMainImage() ?? $drawer->effectiveMainImage();
            $canAdd = $selected && $selected->status === 'active' && $selectedPrice && bccomp($selectedAvailable, '0', 6) > 0;
        @endphp
        <div class="fixed inset-0 z-50 flex justify-end bg-zinc-950/50" wire:click.self="$set('openFamilyId', null)"><aside class="h-full w-full max-w-2xl overflow-y-auto bg-white p-5 shadow-2xl dark:bg-zinc-900" role="dialog" aria-modal="true" aria-labelledby="pos-variation-heading"><div class="flex items-start justify-between"><div><p class="text-xs font-bold uppercase tracking-wide text-cyan-700">{{ __('Choose variation') }}</p><flux:heading id="pos-variation-heading" size="xl" class="mt-1">{{ app()->getLocale() === 'ar' ? $drawer->name_ar : $drawer->name_en }}</flux:heading><p class="mt-1 text-xs text-zinc-500">{{ $selected?->item_code ?: __('Select every option to resolve a SKU') }}</p></div><flux:button wire:click="$set('openFamilyId', null)" variant="ghost" icon="x-mark" aria-label="{{ __('Close') }}" /></div><div class="mt-5 overflow-hidden rounded-2xl bg-zinc-100 dark:bg-zinc-800">@if($selectedImage)<img src="{{ route('pos.products.thumbnail', ['product' => $selectedImage->product_id, 'attachment' => $selectedImage->attachment_id]) }}" alt="" width="640" height="360" class="aspect-video w-full object-cover">@else<div class="flex aspect-video items-center justify-center"><flux:icon name="cube" class="size-12 text-zinc-400" /></div>@endif</div>
        <div class="mt-6 space-y-5">@foreach($drawer->familyOptionGroups as $group)<fieldset><legend class="font-bold">{{ app()->getLocale() === 'ar' ? $group->name_ar : $group->name_en }}</legend><div class="mt-2 flex flex-wrap gap-2">@foreach($group->values as $value)@php($available = $optionAvailability[$group->id][$value->id] ?? false)<button wire:click="selectValue({{ $group->id }}, {{ $value->id }})" @disabled(!$available) class="inline-flex min-h-12 items-center gap-2 rounded-xl border-2 px-4 text-sm font-semibold {{ ($selectedValues[$group->id] ?? null) === $value->id ? 'border-cyan-700 bg-cyan-50 text-cyan-950 dark:bg-cyan-950/30 dark:text-cyan-100' : 'border-zinc-200 dark:border-zinc-700' }} disabled:cursor-not-allowed disabled:opacity-35">@if($value->colour_swatch)<span class="size-5 rounded-full border" style="background-color:{{ $value->colour_swatch }}"></span>@endif{{ app()->getLocale() === 'ar' ? $value->name_ar : $value->name_en }}</button>@endforeach</div></fieldset>@endforeach</div>
        <div class="mt-6 rounded-xl bg-zinc-50 p-4 dark:bg-zinc-950"><div class="flex items-center justify-between gap-3"><div>@if($selectedPrice)<div class="text-2xl font-extrabold"><x-money :amount="$selectedPrice->amount" :currency="$store?->branch?->currency ?? 'EGP'" /></div><p class="mt-1 text-xs text-zinc-500">{{ __('Available') }}: {{ rtrim(rtrim(number_format((float)$selectedAvailable, 3, '.', ''), '0'), '.') }}</p>@else<p class="font-semibold text-amber-700">{{ __('Complete the selection to see price and availability.') }}</p>@endif</div><flux:input wire:model="quantity" type="number" min="1" step="1" :label="__('Quantity')" class="w-28" /></div></div>
        @error('selection')<p class="mt-3 text-sm font-semibold text-rose-600">{{ $message }}</p>@enderror<button wire:click="addSelected" @disabled(!$canAdd) class="mt-5 min-h-14 w-full rounded-xl bg-cyan-700 px-5 text-base font-extrabold text-white disabled:cursor-not-allowed disabled:bg-zinc-300">{{ $canAdd ? __('Add selected SKU to cart') : __('Select an available, priced combination') }}</button></aside></div>
    @endif
</section>
