<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ __('Asset history') }} {{ $asset->code }}</title>@vite(['resources/css/app.css'])<style>@page{size:A4;margin:14mm}@media print{.no-print{display:none!important}.history-section{break-inside:avoid}}</style></head>
<body class="bg-white text-zinc-900"><main class="mx-auto max-w-4xl p-6">
    <div class="no-print mb-5 flex justify-end"><button type="button" class="rounded-md bg-teal-700 px-4 py-2 text-white" onclick="window.print()">{{ __('Print') }}</button></div>
    <header class="flex items-start justify-between gap-4 border-b border-zinc-300 pb-5"><div><h1 class="text-2xl font-bold">{{ __('Rental asset history') }}</h1><p class="mt-1 text-sm">{{ app()->getLocale()==='ar' ? $asset->name_ar : $asset->name_en }} · {{ app()->getLocale()==='ar' ? $asset->store?->name_ar : $asset->store?->name_en }}</p></div><div class="text-end"><div class="font-mono text-xl font-bold">{{ $asset->code }}</div><div class="text-sm">{{ __(str_replace('_', ' ', ucfirst($asset->status))) }}</div></div></header>
    <dl class="mt-6 grid gap-4 text-sm sm:grid-cols-4"><div><dt class="text-zinc-500">{{ __('Condition') }}</dt><dd class="font-semibold">{{ __(ucfirst($asset->condition)) }}</dd></div><div><dt class="text-zinc-500">{{ __('Location') }}</dt><dd class="font-semibold">{{ $asset->location ?: '—' }}</dd></div><div><dt class="text-zinc-500">{{ __('Category') }}</dt><dd class="font-semibold">{{ $asset->category ?: '—' }}</dd></div><div><dt class="text-zinc-500">{{ __('Cost') }}</dt><dd class="font-semibold">@can('rental_assets.cost_view'){{ $asset->cost_value === null ? '—' : number_format((float) $asset->cost_value, 2) }} {{ $asset->cost_currency }}@else{{ __('Restricted') }}@endcan</dd></div></dl>
    <section class="history-section mt-8"><h2 class="font-semibold">{{ __('Reservations') }}</h2><div class="overflow-x-auto"><table class="mt-2 w-full text-sm"><thead><tr class="border-b border-zinc-300"><th class="py-2 text-start">{{ __('Interval') }}</th><th class="py-2 text-start">{{ __('Source') }}</th><th class="py-2 text-start">{{ __('Status') }}</th></tr></thead><tbody>@forelse($asset->reservations as $reservation)<tr class="border-b border-zinc-100"><td class="py-2">{{ $reservation->starts_at }} → {{ $reservation->ends_at }}</td><td class="py-2">{{ $reservation->source_reference ?: '—' }}</td><td class="py-2">{{ __(str_replace('_', ' ', ucfirst($reservation->status))) }}</td></tr>@empty<tr><td colspan="3" class="py-3 text-zinc-500">{{ __('No reservation history.') }}</td></tr>@endforelse</tbody></table></div></section>
    <section class="history-section mt-8"><h2 class="font-semibold">{{ __('Checkout history') }}</h2><div class="overflow-x-auto"><table class="mt-2 w-full text-sm"><thead><tr class="border-b border-zinc-300"><th class="py-2 text-start">{{ __('ID') }}</th><th class="py-2 text-start">{{ __('Checked out') }}</th><th class="py-2 text-start">{{ __('Source') }}</th><th class="py-2 text-start">{{ __('Location') }}</th><th class="py-2 text-start">{{ __('Condition') }}</th></tr></thead><tbody>@forelse($asset->checkouts as $checkout)<tr class="border-b border-zinc-100"><td class="py-2 font-mono">{{ $checkout->id }}</td><td class="py-2">{{ $checkout->checked_out_at?->format('Y-m-d H:i') }}</td><td class="py-2">{{ $checkout->source_reference ?: '—' }}</td><td class="py-2">{{ $checkout->location_after ?: '—' }}</td><td class="py-2">{{ $checkout->condition_before ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="py-3 text-zinc-500">{{ __('No checkout history.') }}</td></tr>@endforelse</tbody></table></div></section>
    <section class="history-section mt-8"><h2 class="font-semibold">{{ __('Return history') }}</h2><div class="overflow-x-auto"><table class="mt-2 w-full text-sm"><thead><tr class="border-b border-zinc-300"><th class="py-2 text-start">{{ __('ID') }}</th><th class="py-2 text-start">{{ __('Returned') }}</th><th class="py-2 text-start">{{ __('Checkout') }}</th><th class="py-2 text-start">{{ __('Condition') }}</th><th class="py-2 text-start">{{ __('Outcome') }}</th></tr></thead><tbody>@forelse($asset->returns as $assetReturn)<tr class="border-b border-zinc-100"><td class="py-2 font-mono">{{ $assetReturn->id }}</td><td class="py-2">{{ $assetReturn->returned_at?->format('Y-m-d H:i') }}</td><td class="py-2 font-mono">{{ $assetReturn->checkout_id }}</td><td class="py-2">{{ $assetReturn->condition_after ?: '—' }}</td><td class="py-2">{{ __(str_replace('_', ' ', ucfirst($assetReturn->outcome))) }}</td></tr>@empty<tr><td colspan="5" class="py-3 text-zinc-500">{{ __('No return history.') }}</td></tr>@endforelse</tbody></table></div></section>
    <section class="history-section mt-8"><h2 class="font-semibold">{{ __('Immutable event history') }}</h2><div class="overflow-x-auto"><table class="mt-2 w-full text-sm"><thead><tr class="border-b border-zinc-300"><th class="py-2 text-start">{{ __('Date') }}</th><th class="py-2 text-start">{{ __('Event') }}</th><th class="py-2 text-start">{{ __('Assessment') }}</th><th class="py-2 text-start">{{ __('Result') }}</th></tr></thead><tbody>@forelse($asset->events as $event)<tr class="border-b border-zinc-100"><td class="py-2">{{ $event->created_at }}</td><td class="py-2">{{ __(ucfirst($event->event_type)) }}</td><td class="py-2">{{ $event->assessment }}</td><td class="py-2">{{ __(str_replace('_', ' ', ucfirst($event->resulting_status ?: $event->status))) }}</td></tr>@empty<tr><td colspan="4" class="py-3 text-zinc-500">{{ __('No asset events.') }}</td></tr>@endforelse</tbody></table></div></section>
</main></body></html>
