<x-layouts::app :title="__('Supplier Return Detail')">
<x-app.page :title="__('Supplier Return Detail')" :description="__('Immutable source, cost, movement, and audit history')" max-width="7xl" class="space-y-6">
    <x-slot:actions><flux:button href="{{ route('purchasing.returns') }}" variant="subtle" icon="arrow-left">{{ __('Supplier returns') }}</flux:button><flux:button href="{{ route('purchasing.returns.print', $return) }}" target="_blank" variant="subtle" icon="printer">{{ __('Print') }}</flux:button></x-slot:actions>
    <div class="grid gap-4 md:grid-cols-3"><flux:card><flux:text>{{ __('Status') }}</flux:text><flux:heading>{{ $return->status }}</flux:heading></flux:card><flux:card><flux:text>{{ __('Original invoice') }}</flux:text><flux:heading>{{ $return->purchaseInvoice?->invoice_number }}</flux:heading></flux:card><flux:card><flux:text>{{ __('Total cost') }}</flux:text><flux:heading>{{ $return->total_amount }}</flux:heading></flux:card></div>
    <flux:card class="space-y-4"><flux:heading size="lg">{{ __('Source and approval') }}</flux:heading><div class="grid gap-4 md:grid-cols-3"><div><flux:text>{{ __('Supplier') }}</flux:text><strong>{{ $return->supplier?->name_en ?: $return->supplier?->name_ar }}</strong></div><div><flux:text>{{ __('Store') }}</flux:text><strong>{{ $return->store?->name }}</strong></div><div><flux:text>{{ __('Reason') }}</flux:text><strong>{{ $return->reason?->code }} — {{ $return->reason?->label_en }}</strong></div><div><flux:text>{{ __('Created by') }}</flux:text><strong>{{ $return->creator?->name }}</strong></div><div><flux:text>{{ __('Submitted by') }}</flux:text><strong>{{ $return->submitter?->name ?: '—' }}</strong></div><div><flux:text>{{ __('Approved by') }}</flux:text><strong>{{ $return->approver?->name ?: '—' }}</strong></div></div></flux:card>
    <flux:card><flux:heading size="lg">{{ __('Lines and original cost') }}</flux:heading><flux:table class="mt-4"><flux:table.columns><flux:table.column>{{ __('Product') }}</flux:table.column><flux:table.column>{{ __('Source line') }}</flux:table.column><flux:table.column>{{ __('Quantity') }}</flux:table.column><flux:table.column>{{ __('Original cost') }}</flux:table.column><flux:table.column>{{ __('Total') }}</flux:table.column></flux:table.columns><flux:table.rows>@foreach($return->lines as $line)<flux:table.row :key="$line->id"><flux:table.cell>{{ $line->product?->name_en ?: $line->product?->name_ar ?: '#'.$line->product_id }}</flux:table.cell><flux:table.cell>#{{ $line->purchase_invoice_line_id }}</flux:table.cell><flux:table.cell>{{ $line->quantity }}</flux:table.cell><flux:table.cell>{{ $line->unit_cost }}</flux:table.cell><flux:table.cell>{{ $line->total_cost }}</flux:table.cell></flux:table.row>@endforeach</flux:table.rows></flux:table></flux:card>
    <div class="grid gap-4 lg:grid-cols-2"><flux:card><flux:heading size="lg">{{ __('Stock movements') }}</flux:heading><div class="mt-4 space-y-3">@forelse($movements as $movement)<div class="rounded-lg border p-3"><div class="flex justify-between"><strong>{{ $movement->movement_type }}</strong><span>#{{ $movement->id }} · {{ $movement->quantity }} @ {{ $movement->unit_cost }}</span></div><flux:text size="sm">{{ $movement->posted_at?->toIso8601String() }} · {{ __('Idempotency') }}: {{ $movement->idempotency_key }}</flux:text></div>@empty<flux:text class="mt-3">{{ __('No stock movement posted yet.') }}</flux:text>@endforelse</div></flux:card><flux:card><flux:heading size="lg">{{ __('Approval timeline') }}</flux:heading><div class="mt-4 space-y-3">@forelse($approvals as $approval)<div class="rounded-lg border p-3"><strong>{{ $approval->requested_action }} · {{ $approval->approval_state->value }}</strong><flux:text size="sm">{{ $approval->requested_at?->toIso8601String() }} · {{ __('Requester') }}: {{ $approval->requester?->name ?: '#'.$approval->requester_id }}</flux:text>@if($approval->approver_id)<flux:text size="sm">{{ __('Approver') }}: {{ $approval->approver?->name ?: '#'.$approval->approver_id }}</flux:text>@endif</div>@empty<flux:text class="mt-3">{{ __('No approval records found.') }}</flux:text>@endforelse</div></flux:card></div>
    <flux:card><flux:heading size="lg">{{ __('Audit timeline') }}</flux:heading><div class="mt-4 space-y-3">@forelse($audits as $audit)<div class="rounded-lg border p-3"><strong>{{ $audit->event }}</strong><flux:text size="sm">{{ $audit->created_at?->toIso8601String() }} · {{ $audit->actor_name ?: __('System') }}</flux:text>@if($audit->reason_code)<flux:text size="sm">{{ __('Reason') }}: {{ $audit->reason_code }}</flux:text>@endif</div>@empty<flux:text class="mt-3">{{ __('No audit events found.') }}</flux:text>@endforelse</div></flux:card>
</x-app.page>
</x-layouts::app>
