<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ __('Invoice') }} {{ $sale->document_number }}</title>@vite(['resources/css/app.css'])<style>@page{size:A4;margin:14mm}@media print{.no-print{display:none!important}}</style></head>
<body class="bg-white text-zinc-900">
<main class="mx-auto max-w-4xl p-6">
    <header class="flex items-start justify-between gap-6 border-b border-zinc-300 pb-5"><div><h1 class="text-2xl font-bold">{{ app()->getLocale() === 'ar' ? ($sale->store->company->name_ar ?: $sale->store->company->name_en) : $sale->store->company->name_en }}</h1><p class="mt-1 text-sm">{{ app()->getLocale() === 'ar' ? $sale->store->name_ar : $sale->store->name_en }}</p></div><div class="text-end"><div class="text-sm text-zinc-500">{{ __('Sales invoice') }}</div><div class="font-mono text-lg font-bold">{{ $sale->document_number }}</div><div class="text-sm">{{ $sale->approved_at?->format('Y-m-d H:i') }}</div></div></header>
    <table class="mt-6 w-full text-sm"><thead><tr class="border-b border-zinc-300"><th class="py-2 text-start">{{ __('Product') }}</th><th class="py-2 text-end">{{ __('Quantity') }}</th><th class="py-2 text-end">{{ __('Original price') }}</th><th class="py-2 text-end">{{ __('Selling price') }}</th><th class="py-2 text-end">{{ __('Discount') }}</th><th class="py-2 text-end">{{ __('Line net') }}</th></tr></thead><tbody>@foreach ($sale->lines as $line)<tr class="border-b border-zinc-100"><td class="py-3">{{ app()->getLocale() === 'ar' ? $line->name_ar : $line->name_en }}<div class="text-xs text-zinc-500">{{ $line->item_code }}@if ($line->is_open_price)<span class="ms-2">· {{ __('Open price') }}: {{ $line->open_price_reason }}</span>@endif</div></td><td class="py-3 text-end tabular-nums">{{ $line->quantity }}</td><td class="py-3 text-end tabular-nums">{{ number_format((float) \App\Modules\Retail\Support\DecimalMoney::round((string) ($line->reference_price ?? $line->unit_price)), 2) }} {{ $sale->currency_code }}</td><td class="py-3 text-end tabular-nums">{{ number_format((float) \App\Modules\Retail\Support\DecimalMoney::round((string) $line->unit_price), 2) }} {{ $sale->currency_code }}</td><td class="py-3 text-end tabular-nums">{{ number_format((float) $line->discount_amount, 2) }} {{ $sale->currency_code }}</td><td class="py-3 text-end font-semibold tabular-nums">{{ number_format((float) $line->net_amount, 2) }} {{ $sale->currency_code }}</td></tr>@endforeach</tbody></table>
    <div class="ms-auto mt-6 w-full max-w-sm space-y-2 text-sm"><div class="flex justify-between"><span>{{ __('Invoice subtotal') }}</span><span>{{ $sale->subtotal }}</span></div><div class="flex justify-between"><span>{{ __('Discount') }}</span><span>{{ $sale->discount_total }}</span></div><div class="flex justify-between"><span>{{ __('Tax') }}@if ($sale->tax_applicable) ({{ $sale->tax_rate_snapshot }}%)@endif</span><span>{{ $sale->tax_total }}</span></div><div class="flex justify-between border-t border-zinc-300 pt-2 font-semibold"><span>{{ __('Invoice total') }}</span><span>{{ $sale->total }} {{ $sale->currency_code }}</span></div><div class="flex justify-between"><span>{{ __('Cash rounding') }}</span><span>{{ $sale->cash_rounding_amount }}</span></div><div class="flex justify-between border-t border-zinc-300 pt-2 text-base font-bold"><span>{{ __('Payable total') }}</span><span>{{ $sale->payable_total }} {{ $sale->currency_code }}</span></div><div class="flex justify-between"><span>{{ __('Applied total') }}</span><span>{{ $sale->paid_total }}</span></div><div class="flex justify-between"><span>{{ __('Change total') }}</span><span>{{ $sale->change_total }}</span></div></div>
    <section class="mt-8 border-t border-zinc-300 pt-4"><h2 class="font-semibold">{{ __('Payments') }}</h2><div class="mt-2 overflow-hidden rounded-lg border border-zinc-200"><table class="w-full text-sm"><thead class="bg-zinc-50"><tr><th class="p-2 text-start">{{ __('Method') }}</th><th class="p-2 text-end">{{ __('Applied amount') }}</th><th class="p-2 text-end">{{ __('Tendered amount') }}</th><th class="p-2 text-end">{{ __('Change') }}</th></tr></thead><tbody>@foreach ($sale->payments as $payment)<tr class="border-t border-zinc-200"><td class="p-2 font-mono">{{ $payment->method_code }}</td><td class="p-2 text-end">{{ $payment->amount }} {{ $sale->currency_code }}</td><td class="p-2 text-end">{{ $payment->tendered_amount ?? '—' }}</td><td class="p-2 text-end">{{ $payment->change_amount }}</td></tr>@endforeach</tbody></table></div></section>
</main><script>window.addEventListener('load', () => window.print());</script></body></html>
