<x-layouts::app :title="__('offline.conflict_title')">
    <div class="mx-auto w-full max-w-4xl space-y-6 p-4 sm:p-6">
        <header class="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-2xl font-bold tracking-tight text-text-primary sm:text-3xl">{{ __('offline.review') }}</h1><p class="mt-2 font-mono text-xs text-text-muted">{{ $transaction->local_uuid }}</p></div><flux:button href="{{ route('offline.conflicts.index') }}" variant="subtle" icon="arrow-left" wire:navigate>{{ __('offline.conflict_title') }}</flux:button></header>
        @php
            $offlineErrors = $errors instanceof \Illuminate\Support\ViewErrorBag
                ? $errors->getBag('default')->messages()
                : (is_array($errors) ? $errors : []);
        @endphp
        @if (isset($offlineErrors['offline'][0]))<flux:callout variant="danger" icon="exclamation-triangle">{{ $offlineErrors['offline'][0] }}</flux:callout>@endif
        <flux:callout variant="warning" icon="shield-exclamation">{{ __('offline.review_notice') }}</flux:callout>
        <section class="rounded-xl border border-border bg-surface p-4 sm:p-5" aria-labelledby="offline-difference-title"><h2 id="offline-difference-title" class="font-semibold text-text-primary">{{ __('offline.conflicts') }}</h2><div class="mt-4 space-y-3">@foreach ($conflicts as $conflict)<div class="grid gap-3 rounded-lg border border-border p-3 sm:grid-cols-3"><div><p class="text-xs text-text-muted">{{ __('offline.field') }}</p><p class="mt-1 font-medium text-text-primary">{{ $conflict->field }}</p></div><div><p class="text-xs text-text-muted">{{ __('offline.local_value') }}</p><p class="mt-1 font-mono text-sm text-text-primary">{{ $conflict->local_value }}</p></div><div><p class="text-xs text-text-muted">{{ __('offline.server_value') }}</p><p class="mt-1 font-mono text-sm text-text-primary">{{ $conflict->server_value }}</p></div></div>@endforeach</div></section>
        <section class="rounded-xl border border-border bg-surface p-4 sm:p-5" aria-labelledby="offline-disposition-title"><h2 id="offline-disposition-title" class="font-semibold text-text-primary">{{ __('offline.disposition') }}</h2><flux:callout class="mt-4" variant="warning" icon="information-circle">{{ __('offline.acceptance_unavailable') }}</flux:callout><form method="POST" action="{{ route('offline.conflicts.resolve', $transaction) }}" class="mt-4 space-y-4" x-data="{ submitting: false }" x-on:submit="submitting = true">@csrf
            <fieldset><legend class="text-sm font-medium text-text-primary">{{ __('offline.disposition') }}</legend><div class="mt-2 flex flex-wrap gap-4"><label class="flex items-center gap-2 text-sm text-text-primary"><input class="rounded border-border text-primary focus:ring-primary" type="radio" name="disposition" value="reject" checked /> {{ __('offline.reject') }}</label></div></fieldset>
            <div><label class="text-sm font-medium text-text-primary" for="offline-reason">{{ __('offline.reason') }}</label><p id="offline-reason-help" class="mt-1 text-xs text-text-muted">{{ __('offline.reason_help') }}</p><textarea id="offline-reason" class="mt-2 block min-h-28 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text-primary shadow-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" name="reason" aria-describedby="offline-reason-help @if(isset($offlineErrors['reason'][0])) offline-reason-error @endif" required minlength="8" maxlength="2000">{{ old('reason') }}</textarea>@if(isset($offlineErrors['reason'][0]))<p id="offline-reason-error" class="mt-1 text-sm text-danger" role="alert">{{ $offlineErrors['reason'][0] }}</p>@endif</div>
            <flux:button type="submit" variant="danger" icon="check" x-bind:disabled="submitting"><span x-show="!submitting">{{ __('offline.record_disposition') }}</span><span x-cloak x-show="submitting">{{ __('Saving') }}</span></flux:button>
        </form></section>
    </div>
</x-layouts::app>
