<x-layouts::app :title="__('Quotations')">
    <x-app.page :title="__('Quotations')" :description="__('Create typed offers that are printable and shareable, with no stock, payment, reservation, wallet, or accounting effect.')" max-width="7xl">
        @if(session('success'))<flux:callout variant="success">{{ session('success') }}</flux:callout>@endif
        @if($errors->any())<flux:callout variant="danger" icon="exclamation-triangle">{{ $errors->first() }}</flux:callout>@endif
        @if(session('share_url'))<flux:callout variant="info"><a class="underline" href="{{ session('share_url') }}">{{ __('Open the protected quotation link') }}</a></flux:callout>@endif
        <flux:callout variant="warning" icon="exclamation-triangle">{{ __('NON-POSTING: a quotation is an offer only. Phase 1 has no one-click conversion and it never changes inventory or financial records.') }}</flux:callout>
        @can('quotations.create')
            <flux:card>
                <flux:heading size="lg">{{ __('New quotation') }}</flux:heading>
                <flux:text class="mt-1 text-sm">{{ __('Retail quotations use catalog products. Party quotations use service or rental-asset lines so retail and Party activity stay separate.') }}</flux:text>
                <form method="POST" action="{{ route('quotations.store') }}" class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                    @csrf<input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}">
                    <flux:select name="activity_type" :label="__('Activity type')" required><flux:select.option value="retail">{{ __('Retail') }}</flux:select.option><flux:select.option value="party">{{ __('Party') }}</flux:select.option></flux:select>
                    <flux:select name="customer_id" :label="__('Customer (optional)')"><flux:select.option value="">{{ __('Walk-in customer') }}</flux:select.option>@foreach($customers as $customer)<flux:select.option value="{{ $customer->id }}">{{ app()->getLocale()==='ar' ? $customer->name_ar : $customer->name_en }} · {{ $customer->phone_display }}</flux:select.option>@endforeach</flux:select>
                    <flux:select name="store_id" :label="__('Store')" required><flux:select.option value="">{{ __('Choose store') }}</flux:select.option>@foreach($stores as $store)<flux:select.option value="{{ $store->id }}">{{ $store->code }} · {{ app()->getLocale()==='ar' ? $store->name_ar : $store->name_en }} ({{ $store->type }})</flux:select.option>@endforeach</flux:select>
                    <flux:input name="valid_until" type="date" :value="old('valid_until', now()->addDays(7)->toDateString())" :label="__('Valid until')" required />
                    <flux:select name="lines[0][line_type]" :label="__('Compatible line type')" required><flux:select.option value="product">{{ __('Retail product') }}</flux:select.option><flux:select.option value="service">{{ __('Party service') }}</flux:select.option><flux:select.option value="asset">{{ __('Party asset') }}</flux:select.option></flux:select>
                    <flux:select name="lines[0][product_id]" :label="__('Catalog product (retail only)')"><flux:select.option value="">{{ __('Choose product') }}</flux:select.option>@foreach($products as $product)<flux:select.option value="{{ $product->id }}">{{ $product->item_code }} · {{ app()->getLocale()==='ar' ? $product->name_ar : $product->name_en }}</flux:select.option>@endforeach</flux:select>
                    <flux:input name="lines[0][description_en]" :value="old('lines.0.description_en')" :label="__('Line description (English)')" required />
                    <flux:input name="lines[0][description_ar]" :value="old('lines.0.description_ar')" :label="__('Line description (Arabic)')" required />
                    <flux:input name="lines[0][quantity]" type="number" step="0.001" min="0.001" :value="old('lines.0.quantity', '1')" :label="__('Quantity')" required />
                    <flux:input name="lines[0][unit_price]" type="number" step="0.01" min="0" :value="old('lines.0.unit_price')" :label="__('Unit price')" required />
                    <flux:textarea name="terms" :label="__('Terms')" rows="2">{{ old('terms') }}</flux:textarea>
                    <flux:textarea name="notes" :label="__('Notes')" rows="2">{{ old('notes') }}</flux:textarea>
                    <div class="flex justify-end sm:col-span-2 lg:col-span-4"><flux:button type="submit" variant="primary">{{ __('Save non-posting draft') }}</flux:button></div>
                </form>
            </flux:card>
        @endcan
        <flux:card class="overflow-hidden p-0"><div class="overflow-x-auto"><table class="data-table min-w-[900px] w-full text-sm"><thead><tr><th>{{ __('Number') }}</th><th>{{ __('Type') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Store') }}</th><th>{{ __('Validity') }}</th><th>{{ __('Total') }}</th><th>{{ __('Status') }}</th><th>{{ __('Actions') }}</th></tr></thead><tbody>
            @forelse($quotations as $quotation)
                <tr class="border-t border-zinc-100 align-top dark:border-zinc-800"><td class="font-mono font-semibold">{{ $quotation->quotation_number }}</td><td>{{ __(ucfirst($quotation->activity_type)) }}</td><td>{{ $quotation->customer ? (app()->getLocale()==='ar' ? $quotation->customer->name_ar : $quotation->customer->name_en) : __('Walk-in') }}</td><td>{{ $quotation->store?->code }}</td><td>{{ $quotation->valid_until?->format('Y-m-d') }}</td><td>{{ number_format((float)$quotation->total, 2) }} {{ $quotation->currency_code }}</td><td><x-status.badge :status="$quotation->status" /></td><td><div class="flex flex-wrap gap-2">
                    @can('quotations.print')<flux:button size="sm" variant="subtle" href="{{ URL::signedRoute('quotations.print', ['quotation' => $quotation->id]) }}">{{ __('Print') }}</flux:button>@endcan
                    @can('quotations.share')<form method="POST" action="{{ route('quotations.share', $quotation) }}">@csrf<flux:button type="submit" size="sm" variant="subtle">{{ __('Share') }}</flux:button></form>@endcan
                    @if($quotation->status==='draft')
                        @can('quotations.edit')<details class="w-full rounded-lg border border-zinc-200 p-3"><summary class="cursor-pointer text-sm font-semibold">{{ __('Edit draft') }}</summary><form method="POST" action="{{ route('quotations.update', $quotation) }}" class="mt-3 grid gap-3">@csrf @method('PUT')
                            <flux:select name="lines[0][line_type]" :label="__('Line type')"><flux:select.option value="product" :selected="$quotation->lines->first()?->line_type === 'product'">{{ __('Retail product') }}</flux:select.option><flux:select.option value="service" :selected="$quotation->lines->first()?->line_type === 'service'">{{ __('Party service') }}</flux:select.option><flux:select.option value="asset" :selected="$quotation->lines->first()?->line_type === 'asset'">{{ __('Party asset') }}</flux:select.option></flux:select>
                            <flux:select name="lines[0][product_id]" :label="__('Catalog product (retail only)')"><flux:select.option value="">{{ __('Choose product') }}</flux:select.option>@foreach($products as $product)<flux:select.option value="{{ $product->id }}" :selected="(int) $quotation->lines->first()?->product_id === (int) $product->id">{{ $product->item_code }} · {{ app()->getLocale()==='ar' ? $product->name_ar : $product->name_en }}</flux:select.option>@endforeach</flux:select>
                            <flux:input name="lines[0][description_en]" :value="$quotation->lines->first()?->description_en" :label="__('Line description (English)')" required /><flux:input name="lines[0][description_ar]" :value="$quotation->lines->first()?->description_ar" :label="__('Line description (Arabic)')" required /><flux:input name="lines[0][quantity]" type="number" step="0.001" :value="$quotation->lines->first()?->quantity" :label="__('Quantity')" required /><flux:input name="lines[0][unit_price]" type="number" step="0.01" :value="$quotation->lines->first()?->unit_price" :label="__('Unit price')" required /><flux:input name="valid_until" type="date" :value="$quotation->valid_until?->format('Y-m-d')" :label="__('Valid until')" required /><flux:textarea name="terms" :label="__('Terms')" rows="2">{{ $quotation->terms }}</flux:textarea><flux:textarea name="notes" :label="__('Notes')" rows="2">{{ $quotation->notes }}</flux:textarea><flux:button type="submit" size="sm">{{ __('Save edit without posting') }}</flux:button>
                        </form></details>@endcan
                        @can('quotations.issue')<form method="POST" action="{{ route('quotations.status', $quotation) }}">@csrf<input type="hidden" name="status" value="issued"><flux:button type="submit" size="sm" variant="primary">{{ __('Issue') }}</flux:button></form>@endcan
                    @endif
                </div></td></tr>
            @empty<tr><td colspan="8"><x-state.empty :title="__('No quotations yet.')" :description="__('Create a typed draft to communicate an offer without posting any operational effect.')" /></td></tr>@endforelse
        </tbody></table></div><div class="border-t border-zinc-200 p-4 dark:border-zinc-700">{{ $quotations->links() }}</div></flux:card>
    </x-app.page>
</x-layouts::app>
