<x-layouts::app :title="$order->order_number">
    <div class="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6">
        <x-page-header :title="$order->order_number" :description="__('Party operating order with authoritative asset reservations and source-linked consumable controls.')">
            <x-slot:actions><flux:button href="{{ route('parties.orders.index') }}" variant="subtle">{{ __('All orders') }}</flux:button><flux:button href="{{ route('parties.bookings.show', $order->party_booking_id) }}" variant="subtle">{{ __('Booking') }}</flux:button></x-slot:actions>
        </x-page-header>
        @if(session('success'))<flux:callout variant="success" icon="check-circle">{{ session('success') }}</flux:callout>@endif
        @if($errors->any())<flux:callout variant="danger" icon="exclamation-triangle">{{ $errors->first() }}</flux:callout>@endif
        <div class="grid gap-4 lg:grid-cols-[1fr_20rem]">
            <flux:card>
                <div class="flex flex-wrap items-start justify-between gap-3"><div><flux:heading size="lg">{{ __('Operational lines') }}</flux:heading><flux:text class="mt-1">{{ $order->booking->booking_number }} · {{ $order->store->name_en }}</flux:text></div><x-status.badge :status="$order->status" /></div>
                <div class="mt-5 overflow-x-auto"><table class="data-table min-w-[900px] w-full text-sm"><thead><tr><th>{{ __('Type') }}</th><th>{{ __('Description') }}</th><th>{{ __('Resource / asset') }}</th><th class="text-end">{{ __('Planned') }}</th><th class="text-end">{{ __('Issued') }}</th><th class="text-end">{{ __('Consumed') }}</th><th class="text-end">{{ __('Returned') }}</th></tr></thead><tbody>@foreach($order->lines as $line)<tr><td>{{ ucfirst(str_replace('_', ' ', $line->line_type)) }}</td><td>{{ $line->description }}</td><td>@if($line->rentalAsset)<span class="font-mono">{{ $line->rentalAsset->code }}</span><span class="mt-1 block text-xs text-text-muted">{{ ucfirst((string) $line->rentalAsset->status) }}</span>@else{{ $line->resource_key ?: __('Not assigned') }}@endif</td><td class="text-end">{{ $line->planned_quantity }}</td><td class="text-end">{{ $line->issued_quantity }}</td><td class="text-end">{{ $line->consumed_quantity }}</td><td class="text-end">{{ $line->returned_quantity }}</td></tr>@endforeach</tbody></table></div>
                <div class="mt-5 border-t border-border pt-4"><flux:heading size="lg">{{ __('Source-linked movement history') }}</flux:heading><div class="mt-3 space-y-2 text-sm">@forelse($order->consumableIssues as $issue)<div class="rounded-lg border border-border p-3"><div class="flex flex-wrap justify-between gap-2"><span class="font-mono">{{ __('Issue') }} #{{ $issue->id }}</span><span>{{ $issue->created_at?->format('Y-m-d H:i') }}</span></div>@foreach($issue->lines as $issueLine)<div class="mt-1 text-text-secondary">{{ __('Product') }} #{{ $issueLine->product_id }} · {{ __('Quantity') }} {{ $issueLine->quantity }} · {{ __('Movement') }} #{{ $issueLine->stock_movement_id }}</div>@endforeach</div>@empty<p class="text-text-muted">{{ __('No consumable issues recorded.') }}</p>@endforelse</div></div>
            </flux:card>
            <aside class="space-y-4">
                <flux:card><flux:heading size="lg">{{ __('Next safe action') }}</flux:heading><div class="mt-4 space-y-3">@if($order->status==='draft')@can('party_operating_orders_consumables.approve')<form method="POST" action="{{ route('parties.orders.release', $order->id) }}">@csrf<flux:button type="submit" variant="primary" class="w-full">{{ __('Release for preparation') }}</flux:button></form>@endcan @elseif(in_array($order->status, ['released','in_progress'], true))<flux:text class="text-sm">{{ __('Complete every consumable reconciliation and every asset checkout, return, and inspection before completion.') }}</flux:text>@can('party_operating_orders_consumables.approve')<form method="POST" action="{{ route('parties.orders.complete', $order->id) }}">@csrf<flux:button type="submit" variant="primary" class="w-full">{{ __('Complete order') }}</flux:button></form>@endcan @elseif($order->status==='completed')<flux:callout variant="success">{{ __('Completed and immutable.') }}</flux:callout>@endif</div></flux:card>
                @if(in_array($order->status, ['released','in_progress'], true))
                    <flux:card><flux:heading size="lg">{{ __('Issue consumable') }}</flux:heading><form method="POST" action="{{ route('parties.orders.issue', $order->id) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}"><flux:select name="line_id" :label="__('Consumable line')" required><flux:select.option value="">{{ __('Choose line') }}</flux:select.option>@foreach($order->lines->where('line_type','consumable') as $line)<flux:select.option value="{{ $line->id }}">{{ $line->description }} · {{ __('remaining') }} {{ bcsub((string)$line->planned_quantity, bcadd((string)$line->issued_quantity, (string)$line->returned_quantity, 6), 6) }}</flux:select.option>@endforeach</flux:select><flux:input name="quantity" type="number" step="0.000001" min="0.000001" :label="__('Quantity')" required /><flux:button type="submit" variant="primary" class="w-full">{{ __('Issue from Party store') }}</flux:button></form></flux:card>
                    @foreach($order->consumableIssues as $issue) @foreach($issue->lines as $issueLine)<flux:card><flux:heading size="lg">{{ __('Return unused quantity') }}</flux:heading><flux:text class="mt-1 text-xs">{{ __('References issue') }} #{{ $issue->id }} · {{ __('Already issued') }} {{ $issueLine->quantity }}</flux:text><form method="POST" action="{{ route('parties.orders.return', $order->id) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="issue_id" value="{{ $issue->id }}"><input type="hidden" name="line_id" value="{{ $issueLine->party_operating_order_line_id }}"><input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}"><flux:input name="quantity" type="number" step="0.000001" min="0.000001" :label="__('Unused quantity')" required /><flux:button type="submit" variant="subtle" class="w-full">{{ __('Return to Party store') }}</flux:button></form></flux:card>@endforeach @endforeach
                    @foreach($order->lines->where('line_type', 'rental_asset') as $line)
                        <flux:card class="border-cyan-200 bg-cyan-50/60 dark:border-cyan-900 dark:bg-cyan-950/20">
                            <flux:heading size="lg">{{ __('Reserved rental asset') }}</flux:heading>
                            <flux:text class="mt-1 text-sm"><span class="font-mono">{{ $line->rentalAsset?->code }}</span> · {{ $line->rentalAsset?->name_en }}</flux:text>
                            <dl class="mt-3 space-y-2 text-xs"><div class="flex justify-between gap-3"><dt>{{ __('Reservation') }}</dt><dd class="font-mono">{{ $line->assetReservation?->id ?: __('Missing') }}</dd></div><div class="flex justify-between gap-3"><dt>{{ __('Checkout') }}</dt><dd>{{ $line->assetCheckout?->id ?: __('Pending') }}</dd></div><div class="flex justify-between gap-3"><dt>{{ __('Return') }}</dt><dd>{{ $line->assetReturn?->id ?: __('Pending') }}</dd></div><div class="flex justify-between gap-3"><dt>{{ __('Inspection') }}</dt><dd>{{ $line->assetInspectionEvent?->id ?: __('Pending') }}</dd></div></dl>
                            <div class="mt-4 space-y-3">
                                @if(!$line->assetCheckout)
                                    <form method="POST" action="{{ route('parties.orders.assets.checkout', [$order->id, $line->id]) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}"><flux:button type="submit" variant="primary" class="w-full">{{ __('Check out through asset system') }}</flux:button></form>
                                @elseif(!$line->assetReturn)
                                    <form method="POST" action="{{ route('parties.orders.assets.return', [$order->id, $line->id]) }}" class="space-y-3">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}"><flux:input name="condition_after" :label="__('Condition after Party use')" value="good" required /><flux:button type="submit" variant="subtle" class="w-full">{{ __('Return for inspection') }}</flux:button></form>
                                @elseif(!$line->assetInspectionEvent)
                                    <form method="POST" action="{{ route('parties.orders.assets.inspect', [$order->id, $line->id]) }}" class="space-y-3">@csrf<flux:select name="resulting_status" :label="__('Inspection outcome')" required><flux:select.option value="available">{{ __('Available') }}</flux:select.option><flux:select.option value="damaged">{{ __('Damaged') }}</flux:select.option><flux:select.option value="under_maintenance">{{ __('Under maintenance') }}</flux:select.option><flux:select.option value="lost">{{ __('Lost') }}</flux:select.option></flux:select><flux:textarea name="assessment" :label="__('Inspection findings')" required /><flux:button type="submit" variant="subtle" class="w-full">{{ __('Record inspection') }}</flux:button></form>
                                @else
                                    <flux:callout variant="success">{{ __('Asset history is complete through inspection.') }}</flux:callout>
                                @endif
                            </div>
                        </flux:card>
                    @endforeach
                @endif
            </aside>
        </div>
    </div>
</x-layouts::app>
